[package]
name = "sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = { version = "0.9.8", features = ["derive", "bright-color"] }
tokio = { version = "1.16.1", features = ["full"] }
